#!/usr/bin/env ruby

ENV['GEM_PATH'] = File.join(File.dirname(__FILE__), "gems")

require "open-uri"
require "rubygems"
require "plork-announce"

unless ARGV.length == 1
  $stderr.puts "usage: plorkup name"
  exit
end
name = ARGV[0]

found = false
PlorkAnnounce.locate(name) do |host, port, desc|
  return if found
  found = true

  url = "http://#{host}:#{port}/"
  puts "Discovered #{name} at #{url}"

  puts "Starting download..."
  data = nil
  begin
    open(url) do |fin|
      puts "Downloading..."
      data = fin.read
    end
  rescue => e
    $stderr.puts "problem! #{e}"
    exit
  end

  puts "Unpacking..."
  begin
    IO.popen("tar vvx", "w") do |fout|
      fout.write(data)
    end
  rescue => e
    $stderr.puts "problem! #{e}"
    exit
  end

  puts "Done."

  exit
end

sleep 10
if found
  sleep 10 while true
else
  $stderr.puts "plorkup timed out"
  exit
end
