--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Configure the backend. This method will be called before droping superuser privileges, so you can do crazy stuff that require godlike powers here.
full_name: Thin::Backends::Base#config
is_singleton: false
name: config
params: ()
visibility: public
