--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::H 
  level: 2
  text: Configure the server
- !ruby/struct:SM::Flow::P 
  body: The process might need to have superuser privilege to configure server with optimal options.
full_name: Thin::Server#config
is_singleton: false
name: config
params: ()
visibility: public
